name: laya
description: LAYA brings the worlds of webtoons and social media together in one place. Share your stories, connect with other creators, and discover new comics to read.
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  chewie: ^1.8.5
  cloud_firestore: ^5.6.3
  file_picker: ^8.1.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_storage: ^12.4.4
  flutter_cache_manager: ^3.4.1
  flutter_carousel_widget: ^2.2.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.14.1
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  http: ^1.2.2
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  infinite_carousel: ^1.1.1
  lucide_icons: ^0.257.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  supabase_flutter: ^2.8.0
  syncfusion_flutter_pdfviewer: ^27.1.57
  uuid: ^4.5.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.14
  change_app_package_name: ^1.4.0
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/onboarding/
