name: laya
description: LAYA brings the worlds of webtoons and social media together in one place. Share your stories, connect with other creators, and discover new comics to read.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  chewie: ^1.8.5
  file_picker: ^8.1.3
  flutter_cache_manager: ^3.4.1
  flutter_carousel_widget: ^2.2.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.14.1
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  infinite_carousel: ^1.1.1
  lucide_icons: ^0.257.0
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.8.0
  syncfusion_flutter_pdfviewer: ^27.1.57
  uuid: ^4.5.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/