// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIdUCRigUBRQ9mMdXJ2ifrC_QFfd0CYhs',
    appId: '1:570357596000:web:b1b5d7c5b470451bf3a805',
    messagingSenderId: '570357596000',
    projectId: 'laya-bluefyre-entertainment',
    authDomain: 'laya-bluefyre-entertainment.firebaseapp.com',
    storageBucket: 'laya-bluefyre-entertainment.firebasestorage.app',
    measurementId: 'G-3XW4VPMY8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1QA2NKKw1QdDBURGsvy6t6OrVQfn5vyY',
    appId: '1:570357596000:android:704c2778b524f052f3a805',
    messagingSenderId: '570357596000',
    projectId: 'laya-bluefyre-entertainment',
    storageBucket: 'laya-bluefyre-entertainment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCataCSILwDERkgmeILzBf0swdUJHh9Vjc',
    appId: '1:570357596000:ios:32cdea74ea052f44f3a805',
    messagingSenderId: '570357596000',
    projectId: 'laya-bluefyre-entertainment',
    storageBucket: 'laya-bluefyre-entertainment.firebasestorage.app',
    iosBundleId: 'com.bluefyreentertainment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCataCSILwDERkgmeILzBf0swdUJHh9Vjc',
    appId: '1:570357596000:ios:8c7eaa2a4ba68e41f3a805',
    messagingSenderId: '570357596000',
    projectId: 'laya-bluefyre-entertainment',
    storageBucket: 'laya-bluefyre-entertainment.firebasestorage.app',
    iosBundleId: 'com.example.laya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIdUCRigUBRQ9mMdXJ2ifrC_QFfd0CYhs',
    appId: '1:570357596000:web:7ba26d26abe29828f3a805',
    messagingSenderId: '570357596000',
    projectId: 'laya-bluefyre-entertainment',
    authDomain: 'laya-bluefyre-entertainment.firebaseapp.com',
    storageBucket: 'laya-bluefyre-entertainment.firebasestorage.app',
    measurementId: 'G-Q32YY8D63P',
  );
}
